# .swiftlint.yml

# 無効化するルール
disabled_rules:
  - trailing_whitespace
  - todo
  - orphaned_doc_comment

# 有効化するオプトインルール
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - empty_collection_literal
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

# 除外するディレクトリ
excluded:
  - .build
  - .swiftpm
  - Pods
  - Carthage
  - DerivedData
  - Package.swift

# ルールのカスタマイズ
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - i
    - j
    - ok

nesting:
  type_level: 2
  function_level: 3

# カスタムルール
custom_rules:
  no_print:
    name: 'No print statements'
    regex: "\\bprint\\s*\\("
    message: 'print() はデバッグ用途でのみ使用してください。本番コードでは Logger を使用してください。'
    severity: warning
